features/urls.py
from django.urls import path
from django.contrib import admin

from features import views

home/urls.py
from django.contrib import admin
from django.urls import path,include
import features
from .views import Index,Register,Login,home,logout,Contact
from features import views
app_name='home'
urlpatterns = [
    path('',Index.as_view(),name='index'),
    path('index',Index.as_view(),name='index'),
    path('home', home, name='home'),

    #path('index',Index.as_view(),name='index'),
    path('register', Register.as_view(), name='register'),
    path('login', Login.as_view(), name='login'),
    path('logout', logout, name='logout'),
    path('contact', Contact.as_view(), name='contact'),
    path('search/',features.views.search),
    path('search/trains',features.views.getTrains),
    path('schedule/',features.views.schedule),
    path('schedule/trains',features.views.getTinfo,name='tr'),
    #path('home', Home.as_view(), name='home'),
    path('search/search/trains/cva/', features.views.cva),
    path('search/book1/', features.views.book1),
    path('search/book1/book/', features.views.book),
    path('cancel/', features.views.cancel),
    path('cancel/cancel/cn/', features.views.cn),
    path('pnr/', features.views.pnr, name="pnr"),
    ]

rail/urls.py
from django.contrib import admin
from django.urls import path,include
from features import views
from home import views
from home.views import Index
app_name='basic'
urlpatterns = [
    path('admin/', admin.site.urls),
    #path('',Index.as_view(),name='index'),
    #path('register/',views.Register,name="reg"),
    #path('login/',,name="login"),
    #path('logout/',views.logout,name="logout"),
    path('',include('home.urls')),
    #path('home/',include('home.urls',namespace="home"),name="home"),


]

features/models.py
from django.db import models

# Create your models here.
class Members(models.Model):
    username=models.CharField(max_length=250)
    password=models.CharField(max_length=500)
    email=models.EmailField(max_length=250)



    def register(self):
        self.save()

    @staticmethod
    def get_member_by_email(email):
        try:
            return Members.objects.get(email=email)
        except:
            return False

    @staticmethod
    def get_member_by_uname(username):
        try:
            return Members.objects.get(username=username)
        except:
            return False

    def doExists(self):
        if Members.objects.filter(email=self.email):
            return True

        return False

    def validateEmail(self):
        email=self.email
        from django.core.validators import validate_email
        from django.core.exceptions import ValidationError
        try:
            validate_email(email)
            return True
        except ValidationError:
            return False

    def __str__(self):
        return self.username

home/models.py
from django.db import models

# Create your models here.
class Trains(models.Model):
    tno=models.CharField(primary_key=True,max_length=50)
    tname=models.CharField(max_length=50)
    rid=models.ForeignKey('Route',on_delete=models.CASCADE)

    def __str__(self):
        return self.tno

class Route(models.Model):
    rid=models.CharField(max_length=50)
    ostation=models.CharField(max_length=50)
    dstation=models.CharField(max_length=50)
    def __str__(self):
        return self.rid

class Station(models.Model):
    sid=models.CharField(primary_key=True,max_length=50)
    sname=models.CharField(max_length=50)
    def __str__(self):
        return self.sid


class RouteStation(models.Model):
    tno=models.ForeignKey('Trains',on_delete=models.CASCADE)
    sid=models.ForeignKey('Station',on_delete=models.CASCADE)
    rid=models.ForeignKey('Route',on_delete=models.CASCADE)
    order=models.IntegerField()
    atime=models.CharField(max_length=50)

class Reservation(models.Model):
    tno=models.ForeignKey('Trains',on_delete=models.CASCADE)
    user=models.CharField(max_length=50)
    nos=models.IntegerField()
    date=models.CharField(max_length=50)
    amt=models.IntegerField()
    cls=models.CharField(max_length=50)
    status=models.CharField(max_length=50)
    pnr=models.CharField(max_length=50)
    src=models.CharField(max_length=50)
    des=models.CharField(max_length=50)




class Payment(models.Model):
    pnr=models.CharField(max_length=50)
    user=models.CharField(max_length=50)
    amt=models.IntegerField()
    mtd=models.CharField(max_length=50)
    date=models.CharField(max_length=50)
    cancel=models.CharField(max_length=50)

features/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms

class Usearch(forms.Form):
    src=forms.CharField(max_length=50)
    des = forms.CharField(max_length=50)

class Trsc (forms.Form):
    tnum=forms.IntegerField()

class AddR(forms.Form):
    rid=forms.CharField(max_length=50)
    ostation=forms.CharField(max_length=50)
    dstation=forms.CharField(max_length=50)

class AddST(forms.Form):
    sid=forms.CharField(max_length=50)
    sname=forms.CharField(max_length=50)

class AddT(forms.Form):
    rid=forms.CharField(max_length=50)
    tno=forms.CharField(max_length=50)
    tname=forms.CharField(max_length=50)

class AddRT(forms.Form):
    tno=forms.CharField(max_length=50)
    sid= forms.CharField(max_length=50)
    rid=forms.CharField(max_length=50)
    order=forms.IntegerField()
    atime=forms.CharField(max_length=50)

class Pnr(forms.Form):
    pnr=forms.CharField(max_length=50)

class Book(forms.Form):
    cls=forms.CharField(max_length=10)
    dt=forms.CharField(max_length=10)

home/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms

class UserLogin(forms.Form):
    username = forms.CharField(max_length=250)
    password = forms.CharField(max_length=16, widget=forms.PasswordInput())


class UserReg(forms.ModelForm):
    number=forms.CharField(required=True)
    class Meta:
        model=User
        fields=['username','password','email','number']

    def save(self, commit=True):
        user = super(UserReg, self).save(commit=False)
        user.number = self.cleaned_data["number"]
        if commit:
            user.save()
        return user

features/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.db.models import Max
from django.template import loader
from .models import Members
from .forms import Trsc,Usearch,AddR,AddST,AddT,AddRT
import json

from home.models import RouteStation,Station,Route,Trains,Reservation,Payment
def getTrains(request):
    if request.method == 'POST':
        form=Usearch(request.POST)
        if form.is_valid():

            data=form.cleaned_data
            src=data['src']
            des=data['des']
            a=RouteStation.objects.filter(sid=des)
            x=[]
            o=0
            for i in a:
                tno=i.tno
                b=RouteStation.objects.filter(tno=tno,sid=src)
                for j in b:
                    if j.order<i.order:
                        x.append(j)
                        o=i.order-j.order

        else:
            return HttpResponse('<h1>invalid Data</h1>')
        return render(request,'features/trains.html',{'data':x,'o':o,'src':src,'des':des})
    return HttpResponse('<h1>Wrong REq</h1>')




def schedule(request):
    a=Trains.objects.all()
    return render(request,'features/schedule.html',{'a':a})

def getTinfo(request):
    form=Trsc(request.GET)
    if form.is_valid():
        data=form.cleaned_data
        tno=data['tnum']
        a=RouteStation.objects.filter(tno=tno).order_by('order')


        return render(request,'features/trinfo.html',{'data':a})

    return HttpResponse('<h1>DAta invalid<h1>')


def search(request):
    a=Station.objects.all()
    return render(request,'features/seat.html',{'a':a})




def cva(request):
    if request.method=='POST':
        tn1=request.POST['tno']
        o=int(request.POST['od'])

        cls=request.POST['cls']
        p=0
        if cls=='AC':
            p=120*o
        if cls=='SL':
            p=80*o
        if cls=='3A':
            p=100*o
        if cls=='2S':
            p=50*o
        dt=request.POST['dt']
        c=0
        a=Reservation.objects.filter(tno=tn1,cls=cls,date=dt)

        for i in a:
            c=c+i.nos
        if c>30:
            x="Waiting-"+str(c-30)
            data = json.dumps({
                'read': x,
                'price': p,
            })
            return HttpResponse(data,content_type='application/json')
        else:
            x="Available-"+str(30-c)
            data = json.dumps({
                'read': x,
                'price': p,
            })
            return HttpResponse(data,content_type='application/json')

def book1(request):
    if(request.method=='POST'):
        dt=request.POST['date']
        src=request.POST['src']
        des=request.POST['des']
        tno=request.POST['bk']
        cls = request.POST['cls'+str(tno)]
        nos=request.POST['nos'+str(tno)]
        pr=request.POST['price'+str(tno)]
        tname=Trains.objects.get(tno=tno).tname
        return render(request,'features/payment.html',{'price':int(pr)*int(nos),'dt':dt,'cls':cls,'tno':tno,'nos':nos,'tname':tname,'src':src,'des':des})


def book(request):

    if request.method=='POST':
        nos=int(request.POST['nos'])
        tno=request.POST['tno']
        dt=request.POST['date']
        tn1=Trains.objects.get(tno=tno)
        cls=request.POST['cls']
        op=request.POST['select']
        tname=request.POST['tname']
        src=request.POST['src']
        des=request.POST['des']
        price=int(request.POST['price'])
        pp=price/nos
        mtd='Paytm'
        if op=='option1':
            crd=request.POST['crd']
            nam=request.POST['nam']
            cvv=request.POST['cvv']
            exp=request.POST['exp']
            mtd='Credit/Debit Card'
            if len(crd)!=16 or len(cvv)!=3:
                return render(request,'features/nopay.html')


        c = 0
        f=0
        pay=Payment()
        pay.user=request.user
        pay.amt=price
        pay.date=dt
        pay.mtd=mtd
        pay.cancel='NO'

        a = Reservation.objects.filter(tno=tno, cls=cls, date=dt)
        c1=Reservation.objects.all()
        cp=0
        for i in c1:
            cp=max(cp,int(i.pnr))
        for i in a:
            c = c + i.nos
        if c<30:
            if nos>(30-c):
                b=Reservation()
                b.cls=cls
                b.tno=tn1
                b.status="C"
                b.nos=30-c
                b.amt=200
                b.date=dt
                b.user=request.user
                b.pnr=cp+1
                b.src=src
                b.des=des
                b.save()
                e = Reservation()
                e.cls = cls
                e.tno = tn1
                e.status = "W"
                e.nos = nos-(30 - c)
                e.amt = price
                e.date = dt
                e.user = request.user
                e.pnr = cp + 1
                e.src=src
                e.des=des
                e.save()
                f=1
            else:
                b = Reservation()
                b.cls = cls
                b.tno = tn1
                b.status = "C"
                b.nos = nos
                b.amt = price
                b.date = dt
                b.user = request.user
                b.pnr = cp + 1
                b.src=src
                b.des=des
                b.save()
                f = 1
        else:
            b = Reservation()
            b.cls = cls
            b.tno = tn1
            b.status = "W"
            b.nos = nos
            b.amt = price
            b.date = dt
            b.user = request.user
            b.pnr = cp + 1
            b.save()
            f=2
        c=0
        a = Reservation.objects.filter(tno=tno, cls=cls, date=dt)
        for i in a:
            c = c + i.nos

        pay.pnr = cp+1
        pay.save()
        return render(request,"features/final.html",{'tname':tname,'tno':tno,'date':dt,'src':src,'des':des,'cls':cls,'pnr':(cp+1),'nos':nos,'dt':dt})



def cancel(request):
    a=Reservation.objects.filter(user=request.user).values('pnr','date','tno','src','des','cls','nos').distinct()
    return render(request,'features/cancel.html',{'res':a})

def cn(request):

    if request.method=='POST':


        pnr=request.POST['id']
        a=Reservation.objects.filter(pnr=pnr)
        z=Payment.objects.filter(pnr=pnr,cancel='NO')
        for j in z:
            amt = j.amt
            j.cancel='YES'
            j.save()

        c=0
        cls='X'

        for i in a:
            if i.status=='C':
                c=c+i.nos
            cls=i.cls
        a.delete()
        a=Reservation.objects.all()
        f=0
        for i in a:
            if i.status=='W' and i.cls==cls:
                if i.nos<=c:
                    c=c-i.nos
                    i.status='C'
                    i.save()
                else:
                    f=1
                    b=Reservation()
                    b.cls = i.cls
                    b.tno = i.tno
                    b.status = "C"
                    b.nos = c
                    b.amt = 200
                    b.date = i.date
                    b.user = i.user
                    b.pnr = i.pnr
                    b.save()
                    i.nos=i.nos-c
                    i.save()
                    c=0
                    break
        return HttpResponse(amt)

def pnr(request):
    if request.method=='POST':
        pnr=request.POST['pnr']
        a=Reservation.objects.filter(pnr=pnr)

        return render(request,'features/pnr.html',{'r':a})


    return render(request,'features/pnr.html')

home/views.py
from django.shortcuts import render
from django.template import loader
from features.models import Members
from django.shortcuts import render,redirect,HttpResponseRedirect,HttpResponse
from .forms import UserLogin,UserReg
from django.contrib import auth
from django.contrib.auth import authenticate,login
#from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.views import View
from django.contrib.auth.hashers import make_password, check_password
# Create your views here.
class Index(View):
    def get(self, request):
        return render(request, "features/index.html")

    def post(self, request):
        return render(request, "feautures/index.html")

def home(request):
    return render(request,'features/home.html')

class Register(View):
    def get(self, request):
        return render(request, "features/register.html")

    def post(self,request):
        postData = request.POST
        username = postData.get('uname')
        email = postData.get('email')
        password = postData.get('psw')
        print(password)

        # validation
        value = {'username': username, 'email': email}
        member = Members(username=username, email=email, password=password)
        err_msg = self.validateMember(member)

        # saving
        if not err_msg:
            member.password = make_password(member.password)
            member.register()
            request.session['username'] = member.username
            request.session['member'] = member.id

            return redirect('/login')
            #return render(request,"features/login.html")
            #return redirect('features/home.html')

            #return render(request, 'features/home.html')
        else:
            data = {'error': err_msg, 'values': value}
            return render(request, "features/register.html",data)

    def validateMember(self,member):
        err_msg = None
        if (not member.username):
            err_msg = "Name Required!"
        elif not member.validateEmail():
            err_msg = 'Enter valid email'
        elif not member.password:
            err_msg = "please create a password"
        elif len(member.password) < 6:
            err_msg = "Password must be 6 char long"
        elif member.doExists():
            err_msg = 'Email Address Already registered..'
        return err_msg


class Login(View):
    def get(self, request):
        #Login.return_url = request.GET.get('return_url')
        return render(request, "features/login.html")

    def post(self, request):

        username = request.POST.get('uname')
        password = request.POST.get('psw')
        member = Members.get_member_by_uname(username)
        print(username,password)
        print(member)
        err_msg = None
        if member:
            print(member.password)
            flag = check_password(password, member.password)
            print(flag)
            if flag:
                request.session['username'] = member.username
                request.session['member'] = member.id
                return render(request, 'features/home.html')
            else:
                err_msg = 'Username or Password invalid1'
        else:
            err_msg = 'Username or Password invalid2'
        return render(request, 'features/login.html', {'error': err_msg})


def logout(request):
    request.session.clear()
    return render(request, 'features/index.html')


class Contact(View):
    def post(self, request):
        return render(request, "features/contact.html")

    def get(self, request):
        return render(request, "features/contact.html")

features/templates/features/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
         <!-- Latest compiled and minified CSS -->
    {% load static %}
    <script type="text/javascript" src="{%static 'js/bootstrap.min.js'%}"></script>
    <script type="text/javascript" src="{%static 'js/jquery-3.3.1.min.js'%}"></script>
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">


    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">
    <style>
        body{
            background-image:url('{% static "images/background"%}');
            background-size:100%;
            background-repeat:no-repeat;
        }
        .sty
        {
            font-family: 'Dancing Script', cursive;
            color:white;
        }
        .row1{




            background-color:rgba(0,0,0,0.6);


        }
    </style>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

features/templates/features/cancel.html
{% extends 'features/srbase.html' %}
{%block body%}
<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <!--<h1 style="text-align:center;font-family:sans-seriff">Current Reservations</h1>-->
      <br><br>  <h1 style="text-align:center" class="sm:text-5xl text-3xl font-medium title-font mb-4 text-gray-900"><b>Train Schedule</b></h1>

        {%csrf_token%}
    <div class="container">
    {% for i in res %}
        <div class="tick" style="font-size:13px;color:white;padding:18px;padding-left:40px; ">

            &nbsp&nbspDate       :{{i.date}}<br/>
            &nbsp&nbspTrain no   :{{i.tno}}<br/>
            &nbsp&nbspPNR        :{{i.pnr}}<br/>
            &nbsp&nbspSrc        :{{i.src}}<br/>
            &nbsp&nbspDes        :{{i.des}}<br/>
                            <button class="btn btn-danger" value="{{i.pnr}}" style="float:right;border-radius:50%;" onclick="y(this.value)"type="submit">Cancel</button></br>

        </div>
            <br/><br/>
        {%endfor%}

</div>
<!--<a href="http://127.0.0.1:8000/home"><button class="btn btn-success">Back To Homepage</button></a>-->
<a href="http://127.0.0.1:8000/home"><button class="sm:text-3xl flex mx-auto mt-16 text-white bg-red-500 border-0 py-4 px-10 focus:outline-none hover:bg-red-700 rounded text-lg">Back To Homepage</button></a><br><br>
     <script>
     function y(vl)
    {



        $.ajax({
            type:'POST',
            url:'cancel/cn/',
            data:{
                    id:vl,
                    csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()

                  },
        success:function(data){

            alert("Cancelled Tickets||Amount Refunded:"+data);
            window.location.href=window.location.href;
                               }
            }
                )

    }
    </script>
{%endblock%}

features/templates/features/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <title>Contact</title>

    <style>
.all-browsers {
  margin: 0;
  padding: 5px;
  background-color: lightgray;
}

.all-browsers > h1, .browser {
  margin: 10px;
  padding: 5px;
}

.browser {
  background: white;
}

.browser > h2, p {
  margin: 4px;
  font-size: 90%;
}

footer {
  text-align: center;
  padding: 3px;
  background-color: rgb(65, 57, 55);
  color: white;
}
</style>
</head>
<body> <body background="{% static 'images/bg9.jpg' %}"></body>

   <header class="text-gray-600 body-font bg-white">
        <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
          <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-red-500 rounded-full" viewBox="0 0 24 24">
              <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
            </svg>
            <span class="ml-3 text-xl">Welcome to R-Booking</span>
          </a>
          <nav class="md:mr-auto md:ml-4 md:py-1 md:pl-4 md:border-l md:border-gray-400    flex flex-wrap items-center text-base justify-center ">

           {% if request.session.member%}
            <a href="http://127.0.0.1:8000/home" class="mr-5 hover:text-gray-900"><b>Home</b></a>
            {% else %}
            <a href="http://127.0.0.1:8000/index" class="mr-5 hover:text-gray-900"><b>Home</b></a>
            {% endif %}
            <a href="schedule" class="mr-5 hover:text-gray-900"><b>Check Schedule</b></a>
            <a href="#about" class="mr-5 hover:text-gray-900"><b>About Us</b></a>
            <a href="contact" class="mr-5 hover:text-gray-900"><b>Contact</b></a>









               </nav>
          {% if request.session.member%}
            <svg fill="none" stroke="red" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10" viewBox="0 0 24 24">
                      <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                      <circle cx="12" cy="7" r="4"></circle>
                    </svg>
            <a class="mr-5 hover:text-gray-900"><b>Welcome {{request.session.username}}</b></a>
            <button class=" text-white inline-flex items-center bg-indigo-700 border-0 py-1 px-3 focus:outline-none hover:bg-indigo-800 rounded text-base mt-4 md:mt-0"><a href="logout" >Log Out</a>
          </button>{% endif %}
      </header>

<br><br><br><br>
 <section class="text-gray-900 body-font relative">
   <center>

<div class="p-2 lg:w-2/3">
<div class="h-full bg-white bg-opacity-80 px-6 pt-16 pb-24 rounded-lg overflow-hidden text-center relative">
            <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900"><b>Contact Us</b></h1>
            <p class="lg:w-2/3 mx-auto leading-relaxed text-base">You can share your queries or problems with us.  We are here to help you...😊</p>

          <div class="lg:w-1/2 md:w-2/3 mx-auto">
            <div class="flex flex-wrap -m-2">
              <div class="p-2 w-1/2">
                <div class="relative">
                  <label for="name" class="leading-7 text-sm text-gray-900"><b>Name</b></label>
                  <input type="text" id="name" name="name" class="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-900 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                </div>
              </div>
              <div class="p-2 w-1/2">
                <div class="relative">
                  <label for="email" class="leading-7 text-sm text-gray-900"><b>Email</b></label>
                  <input type="email" id="email" name="email" class="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-900 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
                </div>
              </div>
              <div class="p-2 w-full">
                <div class="relative">
                  <label for="message" class="leading-7 text-sm text-gray-900"><b>Message</b></label>
                  <textarea id="message" name="message" class="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-900 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 h-32 text-base outline-none text-gray-700 py-1 px-3 resize-none leading-6 transition-colors duration-200 ease-in-out"></textarea>
                </div>
              </div>
              <div class="p-2 w-full">
                <button class="flex mx-auto text-white bg-gray-700 border-0 py-2 px-8 focus:outline-none hover:bg-gray-900 rounded text-lg">Send</button>
              </div>
              <div class="p-2 w-full pt-8 mt-8 border-t border-gray-200 text-center">
                <a class="text-indigo-800"><b>r-booking@gmail.com</b></a><br><br>

                <span class="inline-flex">
                  <a class="text-red-600">
                    <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                      <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
                    </svg>
                  </a>
                  <a class="ml-4 text-red-600">
                    <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                      <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
                    </svg>
                  </a>
                  <a class="ml-4 text-red-600">
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                      <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
                      <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
                    </svg>
                  </a>
                  <a class="ml-4 text-red-600">
                    <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                      <path d="M21 11.5a8.38 8.38 0 01-.9 3.8 8.5 8.5 0 01-7.6 4.7 8.38 8.38 0 01-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 01-.9-3.8 8.5 8.5 0 014.7-7.6 8.38 8.38 0 013.8-.9h.5a8.48 8.48 0 018 8v.5z"></path>
                    </svg>
                  </a>
                </span>
              </div>
            </div></div>
          </div>
</div>
        </div>
</div></center>
      </section>
<br><br><br><br>
  <footer>
  <p>Copyright &copy;R-Booking.com</p>
  <p></p>rbooking@gmail.com</p>
</footer>
</body>
</html>

features/templates/features/final.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ticket Details</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style>
        .det
        {
            background-color:rgba(0,0,0,0.7);
            color:white;
            }

         body
         {
         background-color:powderblue;
         background-size:100% 100%;
         height:650px;
         background-repeat:no-repeat;
         }

    </style>
</head>
<body>
<center>
<h1 style="text-align:center;font-family:sans-seriff;"><b>Tickets Booked</b></h1><br><br>

<div class="container" style="align=center">
    <div class="row">
        <div class="col-lg-7"></div>
        <div class="col-lg-12 det">
    <h3>Ticket Details</h3><br>
    <h4>Train Name   :  <b>       {{tname}}</b><br/><br>
    Train No     :<b>        {{tno}}</b><br/><br>
    PNR          :<b>        {{pnr}}</b><br/><br>
    No of seats  :<b>        {{nos}}</b><br/><br>
    Booking Class:<b>        {{cls}}</b><br/><br>
        Booking Date :       <b>{{dt}}</b><br/></h4><br><br>

    <h4>For Further Enquiry Check PNR</h4><br>
    <a href="{%url 'home:home'%}"><button class="btn btn-success">Back To Homepage</button></a>
    <a href="http://127.0.0.1:8000/pnr"><button class="btn btn-info">Check PNR</button></a><br><br><br><br><br><br>
    </div>

    </div>
    </div>
    </center>

</body>
</html>